#pragma once

// The referenced values are generated by pio-scripts/compiled_constants.py



#include <time.h>

extern const char *__COMPILED_DATE_TIME_UTC_STR__;      // "2026/01/19 12:48:35";
extern const time_t __COMPILED_DATE_TIME_UTC_TIME_T__;  // 0x696e2823ll; // 1768826915
extern const char *__COMPILED_GIT_HASH__;               // "g3189243";
extern const char *__COMPILED_GIT_BRANCH__;             // "v1.5.6";

/* vim:set ts=4 et: */
